max_score and _score are required (and can be null)
elastic/elasticsearch-specification pull request #1144
Opened 2021-12-16 16:27 UTC by swallez

Follow-up to https://github.com/elastic/elasticsearch-specification/pull/1079

The `_score` and `max_score` can be null, but are always present. This PR makes them required.

2021-12-16 16:36 UTC, sethmlarson approved these changes

2021-12-16 16:41 UTC, delvedor approved these changes

2021-12-16 16:53 UTC, delvedor requested changes
Blocking as we have discovered that many yaml tests suggest that this property should be optional.

2021-12-16 17:36 UTC, swallez commented
It's weird to not see these fields in the yaml tests as they are always sent by the ES server.

This could be related to some lenient behavior of the yaml test engine. Putting this PR on hold for now.

2024-06-20 13:35 UTC, pquentin approved these changes
Nearly three years later, YAML test validation no longer suggests those properties should be optional, as 2041/2089 is the current response score.

2024-06-20 13:54 UTC, pquentin approved these changes

2024-06-20 14:25 UTC, swallez commented
`max_score` and `_score` can be `null` (see [here](https://github.com/elastic/elasticsearch/blob/3566ee9a0129394cb23cc40c6af1f19a7fa68193/server/src/main/java/org/elasticsearch/search/SearchHits.java#L301) and [here](https://github.com/elastic/elasticsearch/blob/3566ee9a0129394cb23cc40c6af1f19a7fa68193/server/src/main/java/org/elasticsearch/search/SearchHit.java#L837)) when the score is `NaN`. This is semantically equivalent to a missing value (there's no known score) and is not a "meaningful null", and so should be represented as an optional value in strongly typed languages.

@Anaethelion @l-trotta @flobernd can you make sure your respective code generators correctly interpret a required `double | null` as an optional `double`?

2024-06-20 14:32 UTC, flobernd commented
@swallez I can confirm that the .NET generator converts `X | null` unions to nullable (optional) values (`X?`).

2024-06-20 14:41 UTC, pquentin commented
There are few existing mandatory `| null` in the specification, one example being `IndicatorNode` in the Health Report API.

 * Java uses the `Nullable` annotation: https://github.com/elastic/elasticsearch-java/blob/71d6401c7fb0eb1b80399dd9320e250368c5eff5/java-client/src/main/java/co/elastic/clients/elasticsearch/core/health_report/IndicatorNode.java#L62-L66
 * .NET treats them as Nullable<T>, as mentioned above: https://github.com/elastic/elasticsearch-net/blob/b5fe64620459767f9b2ef751223509c4b45e925e/src/Elastic.Clients.Elasticsearch.Serverless/_Generated/Types/Core/HealthReport/IndicatorNode.g.cs#L32-L35
 * Go uses `omitempty`, which does not appear to use `nil` as I would have naively expected: https://github.com/elastic/go-elasticsearch/blob/3571fa5dd10f462d5902fcc344bc8932c033f734/typedapi/types/indicatornode.go#L36-L37

In any case, since this already exists, I would be in favor of merging anyway.

2024-06-20 14:45 UTC, l-trotta commented
that's a no for java, the result here is just `double`, which is not nullable

2024-06-20 14:47 UTC, l-trotta commented
if java is the only problem I'll assign this one to myself and merge it once I have a fix for it

2024-06-20 14:48 UTC, Anaethelion commented
Go is in the same state as Java, for this particular case it translates to a `Float64`.

2024-09-02 17:10 UTC, pquentin commented
I believe Java is the only language left here since https://github.com/elastic/elastic-client-generator-go/pull/39 was merged.

2024-09-03 07:50 UTC, l-trotta commented
I am still working on this yes

2025-08-28 09:39 UTC, l-trotta commented
sorry I forgot, this was fixed in version 9 of the java client! we can finally merge this

2025-08-28 10:31 UTC, merged