Fix msearch_template Response
elastic/elasticsearch-specification pull request #1178
Opened 2021-12-22 13:57 UTC by philkra

as titled.

2021-12-23 10:15 UTC, delvedor reviewed
@swallez can you take a look at this one? You added this change in https://github.com/elastic/elasticsearch-specification/pull/1034.

2021-12-23 10:27 UTC, swallez commented on specification/_global/msearch/types.ts
> +  | SearchResponse<TDocument>
multisearch response items have a `status` field that indicates the result of each search request. This is present in the [ES source code](https://github.com/elastic/elasticsearch/blob/8754c17a2d6218bce2041cddc572d2a58cef895f/server/src/main/java/org/elasticsearch/action/search/MultiSearchResponse.java#L164) and [the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html#search-multi-search-api-response-body).

2021-12-23 10:40 UTC, swallez requested changes
Looking at the reference material (code + docs), this change seems wrong. What are the recordings that led to it?

2021-12-23 10:40 UTC, swallez commented on specification/_global/msearch/types.ts
> +  | SearchResponse<TDocument>
We need `MultiSearchItem` as multisearch response items have a `status` field that indicates the result of each search request. This is present in the [ES source code](https://github.com/elastic/elasticsearch/blob/8754c17a2d6218bce2041cddc572d2a58cef895f/server/src/main/java/org/elasticsearch/action/search/MultiSearchResponse.java#L164) and explained in [the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html#search-multi-search-api-response-body).

2021-12-23 10:40 UTC, swallez commented on specification/_types/Base.ts
> +  status?: integer
Status is always present in error responses, including in multisearch responses. See [ES code](https://github.com/elastic/elasticsearch/blob/8754c17a2d6218bce2041cddc572d2a58cef895f/server/src/main/java/org/elasticsearch/action/search/MultiSearchResponse.java#L161) and [the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html#search-multi-search-api-response-body) "an object with error message and corresponding status code will be returned in place of the actual search response".

Keeping `error` and `status` required also plays an important role (in the Java client) to disambiguate some non-200 results where ES will return either a valid response or an error depending on the parameters (e.g. delete document that returns 404+error if the index doesn't exist but 404+valid response if the index exist but not the document).

2022-01-25 10:43 UTC, philkra commented
Closing this in favour of https://github.com/elastic/elasticsearch-specification/pull/1320

2022-01-25 10:43 UTC, closed without merging