Create imporft graph of types and namespaces
elastic/elasticsearch-specification pull request #1261
Opened 2022-01-14 09:53 UTC by delvedor

This pr adds a new compiler step that generates two additional JSONs, one with the import graph of every type and another one with the import graph of every namespace.
From this data, we will generate a UI to visualize how different modules interacts with each other.

TODO:
- [x] generate a raw data JSON report
- [ ] generate a graphical report to visualize dependencies

Closes: #339

2022-01-14 09:56 UTC, delvedor commented on compiler/src/steps/import-graph.ts
> +      imported_by: types.map(type => type.name)
TODO: this should be a unique array.

2022-01-14 10:13 UTC, swallez commented on compiler/src/steps/import-graph.ts
> +  for (const current of model.types) {
It's more complex than that, as we have to traverse every `ValueOf` (extends, generics, property types, etc) to build the graph from `TypeName` values.

2022-01-14 13:27 UTC, philkra requested changes

2022-01-14 13:27 UTC, philkra commented on output/schema/import-namespace-graph.json
> +    "namespace": "_global.bulk",
https://github.com/elastic/elasticsearch-specification/pull/1261#discussion_r784709089 assume the same holds true for the namespace. Should be unique

2022-01-17 09:27 UTC, delvedor commented
The import map is not committed in the repo for now, it adds a lot of data that is only used for generating the graph (which is published on GH pages).
We'll generate some markdown representations of the json that will be published on GH pages as well.

2022-01-17 09:36 UTC, swallez approved these changes
LGTM!

2022-01-17 09:57 UTC, philkra approved these changes
LGTM

2022-01-17 10:00 UTC, merged