Updates cat trained models API spec
elastic/elasticsearch-specification pull request #1418
Opened 2022-02-09 17:00 UTC by szabosteve

## Overview

This PR updates the cat trained model API spec.

2022-02-16 08:45 UTC, delvedor requested changes
We are already tracking most cat query parameters here: https://github.com/elastic/elasticsearch-specification/blob/b3e872e566beba79bd34a8d8b54ef857e1278f1a/specification/_spec_utils/behaviors.ts#L91-L132

There is no need to type them again unless you are changing the type :)

2022-02-16 09:43 UTC, szabosteve commented
Thanks @delvedor for the info and for the review. I updated my PR accordingly.

2022-02-17 09:35 UTC, delvedor commented on specification/cat/ml_trained_models/CatTrainedModelsRequest.ts
> +    format?: string
```suggestion
```

You can remove this one, as it's already defined here: https://github.com/elastic/elasticsearch-specification/blob/b3e872e566beba79bd34a8d8b54ef857e1278f1a/specification/_spec_utils/behaviors.ts#L91-L132 and you aren't updating the type.

2022-02-17 09:35 UTC, delvedor commented on specification/cat/ml_trained_models/CatTrainedModelsRequest.ts
> +    v?: boolean
```suggestion

```

Same here.

2022-02-17 10:26 UTC, delvedor approved these changes

2022-02-17 10:47 UTC, merged