Add failures to spec
elastic/elasticsearch-specification pull request #1537
Opened 2022-03-16 13:31 UTC by delvedor

Continuation of #1536.

Fixes: https://github.com/elastic/elasticsearch-specification/issues/928

2022-03-17 09:50 UTC, philkra requested changes

2022-03-17 09:50 UTC, philkra commented on specification/_global/clear_scroll/ClearScrollResponse.ts
> +  failures: [
please rename `failures` to `exceptions` which is more generic.

2022-03-17 12:00 UTC, philkra approved these changes
LGTM

2022-03-22 15:41 UTC, sethmlarson approved these changes

2022-03-23 07:27 UTC, merged