Add new fields to ML GET Trained Model Stats response
elastic/elasticsearch-specification pull request #1541
Opened 2022-03-16 15:18 UTC by davidkyle

https://github.com/elastic/elasticsearch/pull/84628 added some new fields to the ML GET Trained model stats response. Here the types are updated with those new fields

2022-03-16 17:10 UTC, sethmlarson requested changes
Thanks for this, some comments:

2022-03-16 17:10 UTC, sethmlarson commented on specification/ml/_types/TrainedModel.ts
> +   * in the last minute. @Since 8.2.0
Annotation should be `@since 8.2.0`. We typically put these on their own line too.

2022-03-16 17:10 UTC, sethmlarson commented on specification/ml/_types/TrainedModel.ts
> +  average_inference_time_ms_last_minute: double
[From the PR](https://github.com/elastic/elasticsearch/pull/84628/files#diff-ef1e72f9ddf1f055b78b94a380131fe4d3c81a7e1926c9801616a25078a87011R272) this field looks optional?

2022-03-16 17:10 UTC, sethmlarson commented on specification/ml/_types/TrainedModel.ts
> +  /** The peak number of requests processed in a 1 minute period. @Since 8.2.0 */
Same as above.

2022-03-16 17:10 UTC, sethmlarson commented on specification/ml/_types/TrainedModel.ts
> +  throughput_last_minute: integer
Same as above.

2022-03-16 17:10 UTC, sethmlarson commented on specification/ml/_types/TrainedModel.ts
> +  peak_throughput_per_minute: integer
From the PR the `peak_throughput_per_minute` and `throughput_per_minute` appear to be longs instead of integers.

2022-03-17 10:16 UTC, davidkyle commented
> this field looks optional?

This is actually true of many of the fields as some are not reported if the deployment is starting up or in an error state. I've updated the new fields added in this PR and the existing ones that should be optional

2022-03-17 10:17 UTC, davidkyle commented
The validation check is failing I'm not sure why

```
Run actions/checkout@v[2](https://github.com/elastic/elasticsearch-specification/runs/5584050421?check_suite_focus=true#step:4:2)
  with:
    repository: elastic/clients-flight-recorder
    path: ./clients-flight-recorder
    ref: dev
    ssh-strict: true
    persist-credentials: true
    clean: true
    fetch-depth: 1
    lfs: false
    submodules: false
Error: Input required and not supplied: token
```

2022-03-23 10:09 UTC, davidkyle commented
@sethmlarson I've updated the PR can you take another look please

2023-05-17 10:49 UTC, davidkyle commented
Closing as now outdated

2023-05-17 10:49 UTC, closed without merging