Add descriptions for queries H-Q
elastic/elasticsearch-specification pull request #2213
Opened 2023-07-28 14:05 UTC by abdonpijpelink

Relates to https://github.com/elastic/elasticsearch-specification/issues/964

Adds Query DSL descriptions for queries H through Q. Descriptions were sourced from https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html and subpages.

2023-07-31 12:00 UTC, jrodewig requested changes
Thanks for putting this up!

It looks like one of the parameter values is missing some text (https://github.com/elastic/elasticsearch-specification/pull/2213#discussion_r1279192146). I'm also not sure how we're handling formatting for fields without explicit keys (such as `<field>`).

Other than that, this looks good to me. I left several non-blocking nits that you can ignore if wanted.

2023-07-31 12:41 UTC, abdonpijpelink commented on specification/_types/query_dsl/fulltext.ts
> +   * combining the several queries generated from the individual search terms is done using a `dis_max query` with the provided `tie_breaker`.
I was struggling with this one and ended up forgetting to capitalize the "c". Still, it's not a good description. [The original docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/query-dsl-query-string-query.html) don't have an explicit description for tie_breaker, but it is mentioned in the text:

_Since several queries are generated from the individual search terms, combining them is automatically done using a `dis_max` query with a `tie_breaker`._

I think I'll change it into:

_How to combine the queries generated from the individual search terms in the resulting `dis_max` query._

2023-07-31 16:06 UTC, jrodewig commented on specification/_types/query_dsl/fulltext.ts
> +   * combining the several queries generated from the individual search terms is done using a `dis_max query` with the provided `tie_breaker`.
Sounds like a good fix. And yeah — Don't feel obligated to fix all our content debt here.

2023-08-01 11:42 UTC, abdonpijpelink commented
Thanks for the thorough review @jrodewig . I've pushed a change that applies your suggestions.

2023-08-01 11:48 UTC, jrodewig approved these changes
Thanks!

2023-08-01 11:51 UTC, merged