Add downsampling spec for data stream lifecycle
elastic/elasticsearch-specification pull request #2256
Opened 2023-08-29 12:52 UTC by andreidan

This adds the specification for downsampling as part of 
the data stream lifecycle.

The `downsampling` configuration is `nullable` (just like
`data_retention`) and itself can contain a `nullable` list 
of downsampling rounds.

Each round consists of an `after` duration/timevalue field
and the downsample configuration (the `fixed_interval`)

2023-08-29 12:54 UTC, andreidan commented
@elastic/clients-team this build is failing with 
```
build
Input required and not supplied: token
```

Can someone please advise?

2023-08-29 15:17 UTC, JoshMock requested changes
Not sure what that build error is about, but fixing this typo will rerun the job anyway. :slightly_smiling_face:

2023-08-29 15:17 UTC, JoshMock commented on specification/indices/put_data_lifecycle/IndicesPutDataLifecycleRequest.ts
> +    downsamplig?: DataStreamLifecycleDownsampling
```suggestion
    downsampling?: DataStreamLifecycleDownsampling
```

2023-08-29 15:17 UTC, JoshMock commented on output/typescript/types.ts
> +    downsamplig?: IndicesDataStreamLifecycleDownsampling
```suggestion
    downsampling?: IndicesDataStreamLifecycleDownsampling
```

2023-08-29 15:17 UTC, JoshMock commented on output/schema/schema.json
> +            "name": "downsamplig",
```suggestion
            "name": "downsampling",
```

2023-08-30 08:24 UTC, gmarouli approved these changes
LGTM, as discussed offline, we agreed that we should allow the client to nullify the `rounds`. The user can use the `downsampling?: DataStreamLifecycleDownsampling` to express a nullification during template composition. Apart from that 🚀

2023-08-30 09:48 UTC, andreidan commented
Superseeded by https://github.com/elastic/elasticsearch-specification/pull/2259

2023-08-30 09:48 UTC, closed without merging