Search Response has completion_time and _cluster/details
elastic/elasticsearch-specification pull request #2260
Opened 2023-08-29 16:15 UTC by quux00

Updates the spec for the response objects for `POST _async_search`, `GET _async_search/:id`, `GET _async_search/status/:id` and `GET _search`

Two high level changes have happened in 8.10:

1) `completion_time` and `completion_time_in_millis` (async_search only) https://github.com/elastic/elasticsearch/pull/97700

2) Adding `details` metadata to the `_clusters` section of both async and synchronous search responses https://github.com/elastic/elasticsearch/pull/97731

2023-08-31 11:46 UTC, swallez requested changes

2023-08-31 15:00 UTC, quux00 commented on specification/_types/Stats.ts
> +property: ClusterSearchStatusEnum
I was following the docs where it said when defining an enum to put that. I can remove it and see if it still works.

2023-08-31 15:01 UTC, quux00 commented on specification/_types/Stats.ts
> +  took?: long
Yes, a millis timestamp. I'll change it, thanks!

2023-08-31 15:18 UTC, quux00 commented on specification/_types/Stats.ts
> +  took?: long
Oh, I copied the value from the `took` entry in SearchResponse: https://github.com/elastic/elasticsearch-specification/blob/b3a1e6f30b6a0e19b644c406331e1d56bd2907a0/specification/_global/search/SearchResponse.ts#L40

This is the "same" took value (just in a different subsection), so should I have them consistent?

If yes, should I change the above one to `DurationValue<UnitMillis>` also?

2023-08-31 15:37 UTC, quux00 commented on specification/_types/Stats.ts
> +  took?: long
Actually that usage is in a bunch of places. Not sure I want to update all those (?)

```
./specification/fleet/search/SearchResponse.ts:    took: long
./specification/rollup/rollup_search/RollupSearchResponse.ts:    took: long
./specification/_global/search/SearchResponse.ts:  took: long
./specification/_global/knn_search/KnnSearchResponse.ts:    took: long
```

2023-09-01 12:49 UTC, swallez approved these changes
LGTM! Thanks

2023-09-01 12:56 UTC, merged