Make k and num_candidates optional in kNN queries
elastic/elasticsearch-specification pull request #2490
Opened 2024-04-08 13:47 UTC by pquentin

This reflects the changes made in 8.13: https://github.com/elastic/elasticsearch/pull/101209. The current situation forces setting values: https://discuss.elastic.co/t/knnquery-in-java-client/356645/1

2024-04-08 13:52 UTC, pquentin commented
The validation results appear to be worse than what we have on main currently, so I will investigate.

2024-04-08 17:45 UTC, swallez requested changes
`KnnSearch` is good, but there are some discrepancies on `KnnQuery`:
* it must extend `QueryBase` to have the `_name` and `boost` fields (the latter should be removed from the type)
* `num_candidates` should be optional
* `k` and `inner_hits` should be removed.

Can you add these fixes?

2024-04-09 10:44 UTC, pquentin commented
Thanks, done! The CI failure is addressed in https://github.com/elastic/elasticsearch-specification/pull/2492.

2024-04-12 07:36 UTC, l-trotta approved these changes

2024-04-12 07:42 UTC, merged