Improve declaration of untagged unions to allow for generator optimizations
elastic/elasticsearch-specification pull request #2548
Opened 2024-05-08 08:17 UTC by flobernd

Related to #2545

2024-06-12 13:21 UTC, swallez requested changes
Can you add a brief description of this new variant type [in the docs](https://github.com/elastic/elasticsearch-specification/blob/main/docs/modeling-guide.md#variants)?

And mentioning explicitly that this is used for legacy types and should generally avoided as it results in less optimal code generation in client libraries.

2024-06-13 08:05 UTC, flobernd commented
Done.

2024-06-13 11:33 UTC, l-trotta commented
@swallez added a commit to fix openapi generation (also enhanced error logging for the deserialization of the schema.json, thanks @Anaethelion)

2024-06-27 13:25 UTC, flobernd commented
## Spec Meeting 2024/06/27

1. Explicitly name the "deserialization"/untyped variant in the decorator
2. Add a strong validation to disallow adding new "untagged" variants
3. Check flattening of generics

2024-06-28 10:22 UTC, Anaethelion approved these changes
LGTM!

2024-06-28 11:55 UTC, merged