[ML] Update Delete Inference Endpoint for dry_run and force options
elastic/elasticsearch-specification pull request #2602
Opened 2024-06-05 17:04 UTC by maxhniebergall

Following on  https://github.com/elastic/elasticsearch/pull/109123 and https://github.com/elastic/elasticsearch/pull/109384, this change updates the elasticsearch specification to include the dry_run and force options for the Delete Inference Endpoint API.

2024-06-05 21:28 UTC, davidkyle commented on specification/inference/delete/DeleteRequest.ts
> +
```suggestion
query_parameters: {
```

These should be in query_parameters rather than path parts

2024-06-06 13:29 UTC, davidkyle commented on specification/inference/delete/DeleteResponse.ts
> +    dryRunResult: DeleteInferenceEndpointResult
What does `dryRunResult` mean here? Should it be `body: DeleteInferenceEndpointResult` ?

2024-06-06 13:36 UTC, jonathan-buttner requested changes

2024-06-06 13:36 UTC, jonathan-buttner commented on specification/inference/_types/Results.ts
> +  ingest_processors: Array<string>
I think the field is `pipelines` right? That's what I'm seeing in the response:

```
{
    "acknowledged": false,
    "pipelines": [
        "elser"
    ]
}
```

2024-06-06 13:36 UTC, jonathan-buttner commented on specification/inference/delete/DeleteResponse.ts
> +  body: {
Hmm I think this should be:

```
export class Response {
  body: DeleteInferenceEndpointResult
}
```

I don't believe there's a `dryRunResult` field in the response.

2024-06-06 13:46 UTC, maxhniebergall commented
Clearly I don't fully understand what the correspondence between the java code and the specification is. I'm going to do some reading and come back to this.

2024-06-06 16:07 UTC, merged