Added include_named_queries_score to search
elastic/elasticsearch-specification pull request #2729
Opened 2024-07-17 10:45 UTC by l-trotta

Added in [8.8](https://github.com/elastic/elasticsearch/pull/94564), `include_named_queries_score` adds the score to the result of named query. 
In practice, it changes the type of [matched_queries](https://github.com/elastic/elasticsearch-specification/blob/5615a46a870f15fa51edf6a3c4e8c2ed8cc3ebf7/specification/_global/search/_types/hits.ts#L52) in Hit from `string[]` to `string[] | Dictionary<string,double>`, because the server will return a different data structure depending on the value of `include_named_queries_score` in the request. 

After discussing this, we decided that for now strongly typed clients (java, go, .net) won't support it, but we're still adding this to the spec for completeness and for other clients that might be able to support it.

2024-07-17 17:17 UTC, JoshMock commented
Nope, no problems from JS. :+1:

2024-08-02 09:02 UTC, pquentin requested changes
Thank you! This looks great. I confirmed that this does not work as part of the request body.

However, this needs to be added to MultiSearchRequest.ts.

2024-08-02 09:28 UTC, l-trotta commented
@pquentin added it to multisearch, thank you!

2024-08-02 09:48 UTC, pquentin reviewed
Should we also add the performance caveat from the docs?

> Typically, this adds a small overhead to a request. However, using computationally expensive named queries on a large number of hits may add significant overhead.

Also, the `server_default false` annotation is missing.

2024-08-02 15:30 UTC, pquentin approved these changes
Thanks! LGTM.

2024-08-06 09:50 UTC, l-trotta commented
@flobernd @Anaethelion let me know when the generators are ready so that we can merge this

2024-08-06 10:30 UTC, flobernd commented
@l-trotta My generator is adjusted.

2024-08-06 14:08 UTC, Anaethelion commented
@l-trotta all good for me.

2024-08-06 15:19 UTC, merged