Add doc_id; remove out-dated links
elastic/elasticsearch-specification pull request #746
Opened 2021-09-15 23:05 UTC by lcawl

Related to https://github.com/elastic/elasticsearch-specification/pull/732

This PR tests the new [@doc_id ](https://github.com/elastic/elasticsearch-specification/blob/main/docs/modeling-guide.md#doc_id) functionality. The ml.customUrls keyword in this case should resolve to the same type of URL as exists in https://github.com/elastic/kibana/blob/master/src/core/public/doc_links/doc_links_service.ts

I also removed some links to out-dated URLs that are no longer valid or necessary.

2021-09-16 06:13 UTC, delvedor requested changes
LGTM

Can you run `make contrib`?

2021-09-16 15:13 UTC, lcawl commented
> Can you run `make contrib`?

I get this error: `Error: 'custom_settings' has the following unknown annotations: doc_id`. Is there something else I need to do to make it aware of this option?

2021-09-20 12:47 UTC, delvedor reviewed
It looks like that `doc_id` can only live in request definitions, I'll update the compiler!

2021-09-20 13:32 UTC, delvedor commented
Oks, I've merged https://github.com/elastic/elasticsearch-specification/pull/755, please sync with the main branch and run `make contrib` again, sorry for the confusion!

2021-09-21 05:54 UTC, delvedor approved these changes

2021-09-21 05:54 UTC, merged